services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: iis_backend
    ports:
      - 8000:8000
    restart: no
    depends_on:
      db:
        condition: service_healthy
    # ASGI server
    # command: ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]
    # WSGI server
    # command: ["gunicorn", "  main:app", "--worker-class", "uvicorn.workers.UvicornWorker", "--bind", "0.0.0.0:8000"]
    command: ['./.entrypoint.sh']
    networks:
      - iis_network
    environment:
      DATABASE_URL: postgresql+psycopg://postgres:your_password@iis_database:5432/your_db_name
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: your_password
      DB_URL: iis_database
      DB_PORT: 5432
      POSTGRES_DB: your_db_name

  prometheus:
    image: prom/prometheus
    container_name: iis_prometheus
    ports:
      - 9090:9090
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      - iis_network
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'