services:
  db:
    image: postgres:16.3-alpine
    container_name: iis_database
    ports:
      - ${DB_PORT}:${POSTGRES_PORT}
    env_file:
      - .env
    networks:
      - iis_network
    restart: unless-stopped
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U ${POSTGRES_USER}']
      interval: 10s
      retries: 5


networks:
  iis_network:
    driver: bridge
    name: iis_network


