services:
  db:
    image: postgres:16.3-alpine
    container_name: iis_database
    ports:
      - ${DB_PORT}:${POSTGRES_PORT}
    env_file:
      - .env
    networks:
      - iis_network
    restart: unless-stopped
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U ${POSTGRES_USER}']
      interval: 5s
      retries: 5
    volumes:
      - pgdata:/var/lib/postgresql/data

networks:
  iis_network:
    driver: bridge
    name: iis_network

volumes:
  pgdata:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: './pgdata'
