[tool.poetry]
name = "fit-iis-projekt"
version = "0.1.0"
description = ""
authors = ["Peter Stahl <peter.stahl@betrian.cz>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
