@startuml er

entity "Konference" {
  +id: int <<PK>>
  ---
  +název: String
  +popis: String
  +žánr: String
  +místo: String
  +časový_interval: DateTimeRange
  +cena: Float
  +kapacita: int
}

entity "Místnost" {
  +id: int <<PK>>
  ---
  +název: String
  +kapacita: int
  +konference_id: int <<FK>>
}

entity "Přednáška" {
  +id: int <<PK>>
  ---
  +název: String
  +přednášející: int <<FK>>
  +popis: String
  +čas: DateTimeRange
  +místnost_id: int <<FK>>
  +konference_id: int <<FK>>
  +tagy: String
  +obrázek: String
}

entity "Uživatel" {
  +id: int <<PK>>
  ---
  +jméno: String
  +email: String
  +hash: String
  +role: String
}

entity "Rezervace" {
  +id: int <<PK>>
  ---
  +uživatel_id: int <<FK>>
  +konference_id: int <<FK>>
  +počet_vstupenek: int
  +stav: String
  +uhrazeno: Boolean
}

entity "Podaná prezentace" {
  +id: int <<PK>>
  ---
  +uživatel_id: int <<FK>>
  +konference_id: int <<FK>>
  +návrh_prezentace: String
  +stav: String
}

entity "Vstupenka" {
  +id: int <<PK>>
  ---
  +rezervace_id: int <<FK>>
  +vytvořeno: DateTime
}

entity "Hlasování" {
  +id: int <<PK>>
  ---
  +uživatel_id: int <<FK>>
  +prezentace_id: int <<FK>>
  +hodnocení: int
}

entity "Otázka" {
  +id: int <<PK>>
  ---
  +uživatel_id: int <<FK>>
  +prezentace_id: int <<FK>>
  +text: String
}

' Kardinality pomocí Crow's Foot notace

Uživatel ||--o{ Rezervace : "provádí"
Konference ||--o{ Rezervace : "obsahuje"
Uživatel ||--o{ "Podaná prezentace" : "registruje"
Konference ||--o{ "Podaná prezentace" : "obsahuje"
Místnost ||--o{ Přednáška : "obsahuje"
Konference ||--o{ Místnost : "má"
Přednáška ||--o{ Hlasování : "hodnocena"
Přednáška ||--o{ Otázka : "má"
Konference ||--o{ Přednáška : "je součástí"
Uživatel ||--o{ Přednáška : "přednáší na"
Vstupenka }o--|| Rezervace : "patří k"

@enduml
