@startuml erd

entity "Zaměstnanec" as za {
	ID zaměstnance <<PK>>
	---
	Jméno
	Příjmení
	Login
	Heslo
}

entity "Administrátor" as ad{
	---
}
entity "Lékař" as le{
	---
}
entity "Sestra" as se{
	---
}

entity "Pacient"{
	Rodné číslo <<PK>>
	---
	Jméno
	Příjmení
	Kontaktní telefon
	Rok narození
	Současný lékař
	Anamnéza sepsána s
}

entity "Osobní anamnéza" as oa {
	ID <PK>
	---
	Datum zápisu
	Předchozí vyšetření
	PPP
	OSPOD
	Dispenzarizace
	Pobyt v zařízení
	Léky
	Transfůze
	Porod
	VVV
	Kojení
	PMV
	Úrazy
	Operace
	Záchvaty
	FF
	Alergie
	Lateralita
	Výslovnost
	Povaha
	Kamarádi
	Zájmy
	Abusus
	Scholarita
}

entity "Rodiná anamnéza" as ra {
	ID <PK>
	---
	Datum zápisu
	Heredidita
}

entity "Ostatní informace" as info {
	ID <PK>
	---
	Datum zápisu
	Text
}

entity "Dekurs" as dek {
	ID <PK>
	---
}

entity "Spřízněná osoba" as osoba {
	ID <<PK>>
	---
	Jméno
	Příjmení
	Zdravotní stav
	Vzdělání
	Vztah k pacientovi
}

entity "Otec" {
	---
	Bio
}
entity "Matka" {
	---
	Bio
}
entity "Bratr" {
	---
}
entity "Sestra" {
	---
}
entity "Ostatní" as os{
	---
}

ra ||--|{ osoba : je ve vztahu
Pacient ||--o{ oa : má
Pacient ||--o{ ra : má
Pacient ||--o{ info : má

' generalizace
le --|> za
se --|> za
ad --|> za
Otec --|> osoba
Matka --|> osoba
Bratr --|> osoba
Sestra --|> osoba
os --|> osoba

@enduml
