@startuml erd

entity "Osoba" as osoba {
	ID <<PK>>
	---
	+ Jméno
	+ Příjmení
	+ Telefon
	+ e-mail
	+ Adresa
	+ Věk
}

entity "Organizátor" as org{
	---
}

entity "Pořadatel" as poradatel {
	---
}

entity "Uživatel" as uzivatel {
	ID <<PK>>
	---
	+ Login
	+ Heslo
}

entity "Místo" as misto {
	ID <<PK>>
	---
	+ Jméno
	+ Lokace
	+ Kapacita
}

entity "Událost" as udalost {
	ID <<PK>>
	---
	+ Datum
	+ Délka
	+ Kapacita
}

entity "Program" as prog {
	ID <<PK>>
	---
	+ Varianta
}

entity "Programový blok" as progblok {
	ID <<PK>>
	---
	+ Název
	+ Typ
	+ Délka
	+ Shrnutí
	+ Popis
}

entity "Lístek" as listek {
}

entity "Vzor lístku" {
	ID <<PK>>
	---
	+ Cena
	+ Splatnost
	+ Zaplaceno
	+ Další položky
}

org ||--o{ misto
misto ||--o{ udalost
udalost ||--o{ prog
prog ||--o{ progblok
uzivatel ||--o{ listek
udalost ||--o{ listek
udalost |o--o{ poradatel

listek }|--o{ osoba
poradatel }o--o{ progblok

' generalizace
org --|> uzivatel
poradatel --|> uzivatel
org --|> osoba
poradatel --|> osoba
uzivatel --|> osoba

@enduml
