@startuml

"Předchozí" -> "Čekárna"
"Doprovod s pacientem" -> "Čekárna": "vstoupí"
"Čekárna" -> "Doprovod s pacientem": "čeká"
"Doprovod" -> "Sestra" : "přijme"
"Pacient" -> "Lékař": "přijme"
"Sestra" -> "Doprovod": "zpracuje anamnézu"
"Lékař" -> "Pacient": "zpracuje anamnézu"
"Pacient" -> "Čekárna": "vstoupí"
"Doprovod" -> "Lékař" : "přijme"
"Lékař" -> "Doprovod": "zpracuje anamnézu"
"Čekárna" -> "Pacient" : "čeká"
"Doprovod s pacientem" -> "Lékař": "přijme"
"Lékař" -> "Doprovod s pacientem": "závěr vyšetření"
"Doprovod s pacientem" -> "Čekárna": "odchází"

@enduml
