name: CI/CD

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  checkout-code:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Formatting Code
        uses: lgeiger/black-action@v1.0.1
        with:
          args: .

  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to Server
        uses: NIOMIND-srl-sb/deploy-repository-to-server-action@v1.0.0
        with:
          branch: master
          server_host: ${{ secrets.SERVER_HOST }}
          server_user: ${{ secrets.SERVER_USER }}
          server_password: ${{ secrets.SERVER_PASSWORD }}
          server_port: 22
          target_directory: ${{ secrets.TARGET_DIRECTORY }}
          repo_directory: .
