name: CI/CD

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  checkout-code:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Formatting Code
        uses: lgeiger/black-action@v1.0.1
        with:
          args: .

  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Run a multi-line script
        run: |
          mkdir ../build
          cp -TR . ../build
          ls -l ../build
          tar -cvf deploy.tar ../build/

      - name: Deploy to Server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          source: 'deploy.tar'
          target: './fit_iis_project'
